receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
  jaeger:
    protocols:
      grpc:
  hostmetrics:
    collection_interval: 23s
    scrapers:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      process:
processors:
  memory_limiter:
    check_interval: 23s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 13s
exporters:
  debug:
service:
  pipelines:
    traces:
      receivers: [jaeger, otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch]
      exporters: [debug]
