ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

enableAllRules = true

[rule.function-result-limit]
  Disabled = true

[rule.cyclomatic]
  Disabled = true

[rule.argument-limit]
  Disabled = true

[rule.function-length]
  Disabled = true

[rule.cognitive-complexity]
  Disabled = true

[rule.max-public-structs]
  Disabled = true

[rule.line-length-limit]
  Disabled = true

[rule.banned-characters]
  Disabled = true

[rule.file-header]
  Disabled = true

[rule.package-comments]
  Disabled = true

[rule.add-constant]
  Disabled = true

[rule.exported]
  Disabled = true