apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: gateway
spec:
  ports:
    - name: promexporter
      port: 9464
      protocol: TCP
    - name: metrics1
      port: 8888
      protocol: TCP
    - name: metrics2
      port: 4317
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679
    processors:
      batch:
        send_batch_size: 1024
        send_batch_max_size: 1500
        timeout: 0s
    exporters:
      debug:
        # verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:9464"
        resource_to_telemetry_conversion:
          enabled: true
        enable_open_metrics: true
    service:
      extensions: [zpages]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
